### ISSUE TITLE
config.js Bug AWS_LAMBDA_REGIONS

### ISSUE THREAD

**Issue by rhoulay** [jaws-stack/JAWS#29]
I try JAWS with my aws account. But return error: 
```
ResourceNotFoundException: Requested resource not found
```
I find that my aws machine run on 'ap-northeast-1'. The config.js just write aws object with 'us-east-1' like:
```
aws: {
        admin_access_key: process.env.AWS_ADMIN_ACCESS_KEY,
        admin_secret_access_key: process.env.AWS_ADMIN_SECRET_ACCESS_KEY,
        aws_region: 'us-east-1'
    },
```

Change it with: 
```
aws_region: process.env.AWS_LAMBDA_REGIONS
```
that work for me :)

**Comment by bahout** [comment]
same for me

**Comment by austinrivas** [comment]
This is fixed in this pr https://github.com/jaws-stack/JAWS/pull/24

**Comment by ac360** [comment]
I'm back from traveling and I will be looking into this tomorrow.  Thanks for your PR and the suggestions in that thread @austinrivas

**Comment by ac360** [comment]
For the interim, we're going to use the quick fix provided by @austinrivas 

For the longer term view, please see #34
