### ISSUE TITLE
Design proposal: jaws new, jaws routes, jaws deploy

### ISSUE THREAD

**Issue by chourobin** [jaws-stack/JAWS#31]
Hi ac360,

Thanks for making this open source and great work! I have a design proposal, would you be open to making JAWS a standalone CLI to keep a user's app separate? The user can then generate a new app using a convenience generator like `jaws new app-name` (kind of like rails), or they can integrate with their existing app by including it in package.json.

An additional proposal would be to have rails-like convenience methods like `jaws routes` to list all the lambda routes, `jaws new api users/signup` to generate a blank lambda function from a template, and `jaws deploy` to update all the lambda functions as well as compress & upload static assets to s3.

I would be happy to make some PRs but just curious about your thoughts on this.

Thanks!

**Comment by ac360** [comment]
:+1:  Yes, I agree that making the JAWS CLI standalone needs to happen.  This weekend, I plan on moving it to a separate repo. 

Also, I'm a fan of those Rails commands and I would love to incorporate them. 

This weekend, I will be publishing the JAWS Road Map.  I will include your suggestions in the JAWS CLI section.  If you would like to help out with these it would be greatly appreciated.  All source contributors will be publicly acknowledged wherever JAWS has a presence.

If anyone has suggestions for useful commands and overall JAWS CLI design, please write them in this issue for the time being.

**Comment by chourobin** [comment]
Awesome! Looking forward to the roadmap :beers: :+1:

**Comment by nateupstairs** [comment]
This could be out of scope (or you might have already considered it), but has any thought gone into versioning on AWS? Since AWS doesn't support any versioning system, could we have a sort of namespacing config option to preface "staging" or "qa" or some other environment name to the lambda function names when uploading non-prod-ready functions?

**Comment by chourobin** [comment]
@nateupstairs i like that idea too.

**Comment by remicastaing** [comment]
Why not use [yeoman](http://yeoman.io/) to scaffold a jaws app? New lambda function could be created with a dedicated generator (`yo jaws:lambda`) and all the other task (run, test, deploy, etc.) could be done with `gulp`.

**Comment by austinrivas** [comment]
@remi I like yeoman a lot, really easy to work with and build complex
generators / cli tools

**Comment by austinrivas** [comment]
@ac360 I noticed you marked this one as help wanted. Do you want to create another repo in the org that I can start submitting pr's against?

**Comment by ac360** [comment]
@remicastaing @austinrivas I like Yeoman as well.  However, I'm going to investigate a JAWS CLI redesign first.  I think a robust JAWS CLI can significantly reduce time-to-action and get people started right away, without having to mess with anything else.  

For example, getting started with JAWS could/should be as simple as this:

* `npm install jaws-cli -g`
* `jaws new --name new-app`

I'm going to draw out some ideas for a JAWS CLI redesign in the new JAWS-cli repo.  Let's move this discussion here: https://github.com/jaws-stack/JAWS-cli/issues/1
