### ISSUE TITLE
GITTER

### ISSUE THREAD

**Issue by remicastaing** [jaws-stack/JAWS#36]
Not all words/ideas/questions are worth an issue. A Gitter chat room could sometime be the right place to exchange some words.

**Comment by austinrivas** [comment]
+1 gitter has become my go to idle chat

**Comment by chourobin** [comment]
I'll put in my vote for making a slack community.

**Comment by ac360** [comment]
I'll set something up within the next hour.

**Comment by ac360** [comment]
Done!  https://gitter.im/jaws-stack/JAWS
