### ISSUE TITLE
Invoking other Lambda functions

### ISSUE THREAD

**Issue by jwulf** [jaws-stack/JAWS#46]
What's the best way to invoke Lambda functions from JAWS? Should I write something to invoke it via REST, or can I use Lambda.invoke?

**Comment by mbreton** [comment]
IMHO if you want invoke a lambda from a Web app, or mobile app the best way
would be to use the amazon gateway to build a pseudo Rest API.
In this manner, you have less coupling between your client app and the
back-end. BTW in Jaws you will have a swagger json descriptor to aws
gateway generator soon. (cf. #41)

**Comment by jwulf** [comment]
Sorry, I meant invoking a lambda from inside another lambda.

**Comment by mbreton** [comment]
Ok, In this case use the API SDK directly seems a better idea to avoid the
HTTP overload.

**Comment by ac360** [comment]
@jwulf Use the AWS SDK to invoke a lambda function from within another lambda function for best performance.

**Comment by akleiber** [comment]
Invoking one lambda from another lambda via the AWS SDK is also mentioned by AWS in this blog post: https://aws.amazon.com/blogs/developer/invoking-aws-lambda-functions-from-java/
