### ISSUE TITLE
Dependencies added to package.json

### ISSUE THREAD

**Issue by RLC85** [jaws-stack/JAWS#47]
Due to no dependencies I can not `npm install` this repository and run it I am running into `Error: Cannot find module 'XXXXX'`

**Comment by remicastaing** [comment]
@RLC85, did you NPM Link the lib folder as written in https://github.com/jaws-stack/JAWS/wiki/JAWS-Installation#npm-link-lib-with-your-lambda-functions?

**Comment by RLC85** [comment]
Ah! I see I misunderstood the implementation of the project the dependencies for the lib and site folders are split to the package.json files in `jaws/site/package.json` and `jaws/lib/package.json`. I was combining them in the jaws/package.json.

**Comment by ac360** [comment]
@remicastaing Nice Rémi!
