### ISSUE TITLE
Suggestion: Implement JS Standard Style

### ISSUE THREAD

**Issue by ashack293** [jaws-stack/JAWS#53]
I wanted to suggest adoption of [JavaScript Standard Style](https://github.com/feross/standard). This is purely in the interest of enforcing some consistency in the code from many contributors. Since it's pretty early in the codebase's life, it wouldn't be too hard to do, and it may help a lot down the road.

**Comment by callmeStriking** [comment]
I was about to agree with this, but then I saw some questionable choices such as "No semicolons" and "Space after function name". 

For something that calls itself "standard", you'd be hard-pressed to find JS code that uses zero semicolons. Also, people like to put spaces between `if`s and their conditions while removing it from functions, to allow distinguishing between the two visually like 
'''
if (this) {
  thenThat(a,b);
} else {
  otherThing();
}
'''

**Comment by ashack293** [comment]
I agree that some of the formatting choices are not my favorites. I do love my semi-colons. 

But I use Sublime Text, so I installed a package that auto-formats my .js files when I save them: https://packagecontrol.io/packages/StandardFormat . This makes it a lot easier.

**Comment by ac360** [comment]
Update 8/13/15:  

We’re currently working on a document that outlines the specifications for JAWS v1.0.0.  

A proposed resolution to this issue in particular is included in that document.  

Today or tomorrow, we will share the document for everyone to comment on because your feedback is essential.

**Comment by ashack293** [comment]
We're using airbnb's style guide, so this issue can be closed.

**Comment by doapp-ryanp** [comment]
@ashack293 check https://github.com/jaws-stack/JAWS/pull/64 for our proposed implementation / enforcement of airbnb (with 2 tweaks).  Make sure to checkout the README.md cuz our choice of JSCS makes it easy to use with most editors.  FWIW I use WebStorm 11 and its working very nicely.

**Comment by ashack293** [comment]
@doapp-ryanp yeah, I made a comment in the spec referring other Sublime Text users to the SublimeLinter package for enforcement of airbnb. I didn't really care which standard we used, so long as we use one ;)

**Comment by doapp-ryanp** [comment]
Yup - [JSCS overview](http://jscs.info/overview.html) has one too for sublime.  If you use its Airbnb preset and suck in our `.jscsrc` included in the project it will make your life easier IMO.  Totally up to you.

**Comment by ashack293** [comment]
Cool, thanks!
