### ISSUE TITLE
V1: Distinct repos for frontend and backend

### ISSUE THREAD

**Issue by jschr** [jaws-stack/JAWS#79]
Hey guys, JAWS is looking really great can't wait to try out v1. I've been following the doc and am curious if you would consider separating the backend and frontend into their own distinct repos? 

I'm not too familiar yet with JAWS or lambda so I don't know if this is feasible but I find separating the client code from the server code into separate repos much easier to maintain with a larger app, especially when the backend is strictly an API. 

This might also allow for front-end guys (like myself) to contribute easier by extending the core frontend repo. I may also already have the client built and just want JAWS to serve as my backend API or I just want to quickly deploy a static site with no backend using JAWS' cli tools. 

Like I said, I don't really know what implications separating them has but just some food for thought!

**Comment by remicastaing** [comment]
Hi @jschr, there won't be no front and no back end. jaw-cli is a client able to grab separately a front module and some back end modules. Take a look at https://github.com/jaws-stack/JAWS/tree/v1.0.

**Comment by jschr** [comment]
Ah ok, after rereading the v1 spec doc I think I misinterpreted the **scafolding** section. 

So am I correct that the use case I described above I would create 2 JAWS apps (one for back and one for front) and simply install the applicable modules?

**Comment by ac360** [comment]
@jschr Glad you arrived at the party :)  Yes, JAWS V1 is nothing but some empty folders, a powerful CLI and a Module system.

We think the best organizational tiers for the jaws-modules are:

* A single lambda function can be a module
* A directory with a group of lambda functions and some other folders can also be a module
* The entire front folder can also be a module.  This is the least developed idea.  Essentially, you will be able to run **jaws install https://github.com/jaws-stack/JAWS/jaws-react-front** to replace the **front** folder with the module at the specified url.  What this means is that we need some front-end modules for JAWS.  Especially, a React one.  It should consist of a simple React boilerplate app and integrate handy AWS-SDK for the browser functions.

**Comment by remicastaing** [comment]
@jschr, the basic steps to write a JAWS app will be `jaws new`, then grab some jaws modules for the back end (they will be downloaded in `\back`) and grab a front module (downloaded in `\front`).

**Comment by jschr** [comment]
@ac360 thanks for the clarification, this is awesome! Really excited for the v1 release. 

Do you have any front-end module examples you can share? 

I realize you've got a lot on your plate with v1 so no worries if not and I will anxiously await for the release!

**Comment by jschr** [comment]
Closing since not an issue :)

**Comment by ac360** [comment]
No front-end modules yet.  Although, any front-end boilerplate works.  JAWS gives you a REST API just like anything else.
