### ISSUE TITLE
Any ETA on v1.0?

### ISSUE THREAD

**Issue by eahefnawy** [jaws-stack/JAWS#91]
I've downloaded and tested JAWS (master) and it's working great. Now I'm ready to dig deeper and create some modules/lambda functions for image resize, payments, twilio...etc. However, looking at the v1.0 specs on google docs, I'm not sure if I should wait for v1.0 for a more "stable" architecture, or is it safe to write some modules now and they should "probably" work with v1.0?

I know that @ac360 and @doapp-ryanp are committing hardcore right now on v1.0. Should I shift my focus into helping you guys on core instead of the modules?

Thoughts...?

**Comment by doapp-ryanp** [comment]
Roughly 1 week away. Check [our doc](https://docs.google.com/document/d/1SeTgtsQc620vcwgGMZ4F2yuWVf-A3JmpTn1VT8pKYsA/edit#)

Hold tight we will be opening things up for help soon....

**Comment by eahefnawy** [comment]
haha yeah I've seen the "1 week away" announcement, but wasn't sure **when** it was announced.

Thanks for your hard effort guys! I'll be waiting ;)

**Comment by doapp-ryanp** [comment]
oh yea duh, no frame of ref :) I've updated the doc.  Thanks!
